name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: ['**'] # Run workflows for pull requests to *any* branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v22

      - name: Build release
        run: nix develop --command make
